[package]
name = "advault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "21"
soroban-token-sdk = "21"
verifier_registry = { path = "../verifier_registry" } 

[dev-dependencies]
soroban-sdk = { version = "21", features = ["testutils"] }
